# Generated by Django 3.1.6 on 2021-04-20 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='FriendsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_list', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_is_complete', models.BooleanField(default=False)),
                ('full_name', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(default='testing@testing.com', max_length=255)),
                ('food', models.CharField(default='Undeclared', max_length=50)),
                ('major', models.CharField(default='Undeclared', max_length=50)),
                ('movie', models.CharField(default='Undeclared', max_length=50)),
                ('bio', models.CharField(default='empty', max_length=10000)),
                ('imageFile', models.ImageField(blank=True, null=True, upload_to='profile-images', verbose_name='Profile Image')),
                ('googleProfileImageUrl', models.URLField(null=True)),
                ('friends', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.friendslist')),
                ('hobbies', models.ManyToManyField(blank=True, to='users.Choice')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
