language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install spacy
  - python -m pip install -U channels
  - python3 -m pip install channels_redis
  - python -m spacy download en_core_web_sm
  - python manage.py collectstatic --noinput

# command to run tests
script:
  - python manage.py test 